version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    environment:
      - REACT_APP_APIKEY=${API_KEY}
    ports:
      - "8000:3000"
    depends_on:
      - node
  node:
    image: node:latest